#!/usr/bin/bash
# Usage: ./send <recipient_name> <message>
#
# Send messasge but also refresh the DH points by sending and trying to receive a new point

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/guardrails.sh"
source "$SCRIPT_DIR/../lib/constants.sh"
source "$SCRIPT_DIR/../lib/parse.sh"
require_cmd openssl base64 gmi notmuch

DANGER_USER_other_person="$1"
DANGER_USER_message="$2"

DANGER_USER_other_person=$(parse_known_person "$DANGER_USER_other_person")
# Check if it's directory exists:
if [ ! -d "$CONTACTS_DIR/$DANGER_USER_other_person" ]; then
    die "Error: User '$DANGER_USER_other_person' does not exist. Please add them first using ./add_contact"
fi
other_person="$DANGER_USER_other_person"

# Lazy send point
# If there is not point for that person, send one
#if [ -z "$(ls -A "$CONTACTS_DIR/$other_person/$DH_MY_POINTS" 2>/dev/null)" ]; then
#    echo "No DH point found for $other_person, sending one before the message..."
#    "$SCRIPT_DIR/../send_dh_point.sh" "$other_person"
#    echo "DH point sent to $other_person"
#fi
## If there is no received point for that person, try to fetch one
#if [ -z "$(ls -A "$CONTACTS_DIR/$other_person/$DH_RECEIVED_POINTS" 2>/dev/null)" ]; then
#    echo "No received DH point found for $other_person, trying to fetch one..."
#    "$SCRIPT_DIR/../receive_dh_point.sh" "$other_person"
#    if [ -z "$(ls -A "$CONTACTS_DIR/$other_person/$DH_RECEIVED_POINTS" 2>/dev/null)" ]; then
#        die "No received DH point found for $other_person after fetching, cannot send message securely"
#    fi
#    echo "Received DH point from $other_person"
#fi
"$SCRIPT_DIR/../send_dh_point.sh" "$other_person"
"$SCRIPT_DIR/../receive_dh_point.sh" "$other_person"

# TODO: Parse message
message=$DANGER_USER_message

"$SCRIPT_DIR/../send_message.sh" "$other_person" "$message"